# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI tarea final

on:
  push:
    branches: [ "feature-ms-antonioZelada-mensaje" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build
      run: |
          chmod +x gradlew
          ./gradlew build
    - name: Run Tests
      run: ./gradlew test
    - name: Convert to non-shallow clone
      run: |
          git fetch --unshallow
    - name: Analisis sonarcloud
      run: |
        ./gradlew build sonar -Dsonar.token=${{ secrets.TOKENSONARCLOUDTAREAFINAL }}
    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      env:
          SONAR_TOKEN: ${{ secrets.TOKENSONARCLOUDTAREAFINAL }} 
          SONAR_HOST_URL: https://sonarcloud.io
      with:
          scanMetadataReportFile: build/sonar/report-task.txt   
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      
